### Добавление площадки
POST http://localhost:8080/api/areas
Content-Type: application/json

{
  "name": "Hall_01"
}

### Получение событий

GET http://localhost:8080/api/events

### Получение одного события

GET http://localhost:8080/api/events/5

### Регистрация пользователя

POST localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "Frank.irina@gmail.com",
  "password": "Qwerty008!"
}

### Добавление события на площадку

POST localhost:8080/api/areas/1/events
Content-Type: application/json

{
  "name": "Concert",
  "description": "Bi 2 band",
  "dayOfWeek": "FRIDAY",
  "startTime": "19:00",
  "finishTime": "23:00"
}

### Добавление существующего события на площадку

POST localhost:8080/api/areas/1/events
Content-Type: application/json

{
  "existsEventId": 12
}


### Получение всех событий площадки

GET localhost:8080/api/areas/1/events

### Удаление события из площадки

DELETE localhost:8080/api/areas/1/events/12

### Редактирование мероприятия

PUT localhost:8080/api/areas/1/events/12
Content-Type: application/json

{
  "name": "Conference",
  "description": "FrontEnd LevelUp",
  "startTime": "12:00",
  "finishTime": "15:00",
  "dayOfWeek": "FRIDAY"
}

### Добавление участника в мероприятие

POST localhost:8080/api/events/13/members
Content-Type: application/json

{
  "userId": 1
}

### Получение всех участников мероприятия

GET localhost:8080/api/events/11/members

