### Добавление площадки
POST http://localhost:8080/api/areas
Content-Type: application/json

{
  "name": "Hall_01"
}

### Получение событий

GET http://localhost:8080/api/events

### Получение одного события

GET http://localhost:8080/api/events/5

### Регистрация пользователя

POST localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "Frank.irina@gmail.com",
  "password": "Qwerty008!"
}

### Добавление события на площадку

POST localhost:8080/api/areas/1/events
Content-Type: application/json

{
  "name": "Conference",
  "description": "FrontEnd LevelUp",
  "dayOfWeek": "FRIDAY",
  "startTime": "13:00",
  "finishTime": "16:00"
}

